// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for FehlerKategorie.
const (
	AKKUDEFEKT     FehlerKategorie = "AKKU_DEFEKT"
	DISPLAYSCHADEN FehlerKategorie = "DISPLAY_SCHADEN"
	KEINFEHLER     FehlerKategorie = "KEIN_FEHLER"
	SOFTWAREOS     FehlerKategorie = "SOFTWARE_OS"
	TASTATURDEFEKT FehlerKategorie = "TASTATUR_DEFEKT"
)

// Valid indicates whether the value is a known member of the FehlerKategorie enum.
func (e FehlerKategorie) Valid() bool {
	switch e {
	case AKKUDEFEKT:
		return true
	case DISPLAYSCHADEN:
		return true
	case KEINFEHLER:
		return true
	case SOFTWAREOS:
		return true
	case TASTATURDEFEKT:
		return true
	default:
		return false
	}
}

// FehlerKategorie defines model for FehlerKategorie.
type FehlerKategorie string

// Laptop defines model for Laptop.
type Laptop struct {
	Fehler FehlerKategorie `json:"fehler"`

	// Id Example: 1234
	Id     int           `json:"id"`
	ItLogs *[]LogEintrag `json:"it_logs,omitempty"`

	// Marke Example: HP
	Marke string `json:"marke"`

	// Name Example: HP EliteBook 840
	Name string `json:"name"`

	// Os Example: Windows 11
	Os string `json:"os"`
}

// LaptopInput defines model for LaptopInput.
type LaptopInput struct {
	Fehler FehlerKategorie `json:"fehler"`

	// Marke Example: HP
	Marke string `json:"marke"`

	// Name Example: HP EliteBook 840
	Name string `json:"name"`

	// Os Example: Windows 11
	Os string `json:"os"`
}

// LogEintrag defines model for LogEintrag.
type LogEintrag struct {
	// Bearbeiter Example: m.mustermann
	Bearbeiter string `json:"bearbeiter"`

	// Id Example: 1
	Id int `json:"id"`

	// Notiz Example: Ger├ñt erfolgreich repariert.
	Notiz string `json:"notiz"`

	// Timestamp Example: 2026-09-02T10:15:00Z
	Timestamp time.Time `json:"timestamp"`
}

// LogEintragInput defines model for LogEintragInput.
type LogEintragInput struct {
	// Bearbeiter Example: m.mustermann
	Bearbeiter string `json:"bearbeiter"`

	// Notiz Example: Ger├ñt erfolgreich repariert.
	Notiz string `json:"notiz"`
}

// GetLaptopsParams defines parameters for GetLaptops.
type GetLaptopsParams struct {
	Fehler *FehlerKategorie `form:"fehler,omitempty" json:"fehler,omitempty"`
}

// PostLaptopsJSONRequestBody defines body for PostLaptops for application/json ContentType.
type PostLaptopsJSONRequestBody = LaptopInput

// PutLaptopsIdJSONRequestBody defines body for PutLaptopsId for application/json ContentType.
type PutLaptopsIdJSONRequestBody = LaptopInput

// PostLaptopsIdLogsJSONRequestBody defines body for PostLaptopsIdLogs for application/json ContentType.
type PostLaptopsIdLogsJSONRequestBody = LogEintragInput

// PutLaptopsIdLogsLogIdJSONRequestBody defines body for PutLaptopsIdLogsLogId for application/json ContentType.
type PutLaptopsIdLogsLogIdJSONRequestBody = LogEintragInput

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// GetLaptops Liste aller Laptops abrufen
	//
	// Corresponds with GET /laptops (the `GetLaptops` operationId).
	GetLaptops(ctx context.Context, params *GetLaptopsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostLaptopsWithBody Neuen Laptop zur Reparatur erfassen
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /laptops (the `PostLaptops` operationId).
	PostLaptopsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostLaptops Neuen Laptop zur Reparatur erfassen
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /laptops (the `PostLaptops` operationId).
	PostLaptops(ctx context.Context, body PostLaptopsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteLaptopsId Reparierten oder ausgemusterten Laptop l├Âschen
	//
	// Corresponds with DELETE /laptops/{id} (the `DeleteLaptopsId` operationId).
	DeleteLaptopsId(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetLaptopsId Einzelnen Laptop samt Logs abrufen
	//
	// Corresponds with GET /laptops/{id} (the `GetLaptopsId` operationId).
	GetLaptopsId(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutLaptopsIdWithBody Laptop-Daten oder Fehlerstatus aktualisieren
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PUT /laptops/{id} (the `PutLaptopsId` operationId).
	PutLaptopsIdWithBody(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutLaptopsId Laptop-Daten oder Fehlerstatus aktualisieren
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with PUT /laptops/{id} (the `PutLaptopsId` operationId).
	PutLaptopsId(ctx context.Context, id int, body PutLaptopsIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostLaptopsIdLogsWithBody IT-Log-Eintrag hinzuf├╝gen
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /laptops/{id}/logs (the `PostLaptopsIdLogs` operationId).
	PostLaptopsIdLogsWithBody(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostLaptopsIdLogs IT-Log-Eintrag hinzuf├╝gen
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /laptops/{id}/logs (the `PostLaptopsIdLogs` operationId).
	PostLaptopsIdLogs(ctx context.Context, id int, body PostLaptopsIdLogsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteLaptopsIdLogsLogId IT-Log-Eintrag l├Âschen
	//
	// Corresponds with DELETE /laptops/{id}/logs/{logId} (the `DeleteLaptopsIdLogsLogId` operationId).
	DeleteLaptopsIdLogsLogId(ctx context.Context, id int, logId int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutLaptopsIdLogsLogIdWithBody Existierenden IT-Log-Eintrag aktualisieren
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PUT /laptops/{id}/logs/{logId} (the `PutLaptopsIdLogsLogId` operationId).
	PutLaptopsIdLogsLogIdWithBody(ctx context.Context, id int, logId int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutLaptopsIdLogsLogId Existierenden IT-Log-Eintrag aktualisieren
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with PUT /laptops/{id}/logs/{logId} (the `PutLaptopsIdLogsLogId` operationId).
	PutLaptopsIdLogsLogId(ctx context.Context, id int, logId int, body PutLaptopsIdLogsLogIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetLaptops Liste aller Laptops abrufen
//
// Corresponds with GET /laptops (the `GetLaptops` operationId).
func (c *Client) GetLaptops(ctx context.Context, params *GetLaptopsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetLaptopsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostLaptopsWithBody Neuen Laptop zur Reparatur erfassen
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /laptops (the `PostLaptops` operationId).
func (c *Client) PostLaptopsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostLaptopsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostLaptops Neuen Laptop zur Reparatur erfassen
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /laptops (the `PostLaptops` operationId).
func (c *Client) PostLaptops(ctx context.Context, body PostLaptopsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostLaptopsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeleteLaptopsId Reparierten oder ausgemusterten Laptop l├Âschen
//
// Corresponds with DELETE /laptops/{id} (the `DeleteLaptopsId` operationId).
func (c *Client) DeleteLaptopsId(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteLaptopsIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetLaptopsId Einzelnen Laptop samt Logs abrufen
//
// Corresponds with GET /laptops/{id} (the `GetLaptopsId` operationId).
func (c *Client) GetLaptopsId(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetLaptopsIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PutLaptopsIdWithBody Laptop-Daten oder Fehlerstatus aktualisieren
//
// Takes any type of body and a specified content type.
//
// Corresponds with PUT /laptops/{id} (the `PutLaptopsId` operationId).
func (c *Client) PutLaptopsIdWithBody(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutLaptopsIdRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PutLaptopsId Laptop-Daten oder Fehlerstatus aktualisieren
//
// Takes a body of the `application/json` content type.
//
// Corresponds with PUT /laptops/{id} (the `PutLaptopsId` operationId).
func (c *Client) PutLaptopsId(ctx context.Context, id int, body PutLaptopsIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutLaptopsIdRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostLaptopsIdLogsWithBody IT-Log-Eintrag hinzuf├╝gen
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /laptops/{id}/logs (the `PostLaptopsIdLogs` operationId).
func (c *Client) PostLaptopsIdLogsWithBody(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostLaptopsIdLogsRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostLaptopsIdLogs IT-Log-Eintrag hinzuf├╝gen
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /laptops/{id}/logs (the `PostLaptopsIdLogs` operationId).
func (c *Client) PostLaptopsIdLogs(ctx context.Context, id int, body PostLaptopsIdLogsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostLaptopsIdLogsRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeleteLaptopsIdLogsLogId IT-Log-Eintrag l├Âschen
//
// Corresponds with DELETE /laptops/{id}/logs/{logId} (the `DeleteLaptopsIdLogsLogId` operationId).
func (c *Client) DeleteLaptopsIdLogsLogId(ctx context.Context, id int, logId int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteLaptopsIdLogsLogIdRequest(c.Server, id, logId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PutLaptopsIdLogsLogIdWithBody Existierenden IT-Log-Eintrag aktualisieren
//
// Takes any type of body and a specified content type.
//
// Corresponds with PUT /laptops/{id}/logs/{logId} (the `PutLaptopsIdLogsLogId` operationId).
func (c *Client) PutLaptopsIdLogsLogIdWithBody(ctx context.Context, id int, logId int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutLaptopsIdLogsLogIdRequestWithBody(c.Server, id, logId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PutLaptopsIdLogsLogId Existierenden IT-Log-Eintrag aktualisieren
//
// Takes a body of the `application/json` content type.
//
// Corresponds with PUT /laptops/{id}/logs/{logId} (the `PutLaptopsIdLogsLogId` operationId).
func (c *Client) PutLaptopsIdLogsLogId(ctx context.Context, id int, logId int, body PutLaptopsIdLogsLogIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutLaptopsIdLogsLogIdRequest(c.Server, id, logId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetLaptopsRequest constructs an http.Request for the GetLaptops method
func NewGetLaptopsRequest(server string, params *GetLaptopsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/laptops")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Fehler != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "fehler", *params.Fehler, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostLaptopsRequest calls the generic PostLaptops builder with application/json body
func NewPostLaptopsRequest(server string, body PostLaptopsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostLaptopsRequestWithBody(server, "application/json", bodyReader)
}

// NewPostLaptopsRequestWithBody constructs an http.Request for the PostLaptops method, with any body, and a specified content type
func NewPostLaptopsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/laptops")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteLaptopsIdRequest constructs an http.Request for the DeleteLaptopsId method
func NewDeleteLaptopsIdRequest(server string, id int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/laptops/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetLaptopsIdRequest constructs an http.Request for the GetLaptopsId method
func NewGetLaptopsIdRequest(server string, id int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/laptops/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutLaptopsIdRequest calls the generic PutLaptopsId builder with application/json body
func NewPutLaptopsIdRequest(server string, id int, body PutLaptopsIdJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutLaptopsIdRequestWithBody(server, id, "application/json", bodyReader)
}

// NewPutLaptopsIdRequestWithBody constructs an http.Request for the PutLaptopsId method, with any body, and a specified content type
func NewPutLaptopsIdRequestWithBody(server string, id int, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/laptops/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostLaptopsIdLogsRequest calls the generic PostLaptopsIdLogs builder with application/json body
func NewPostLaptopsIdLogsRequest(server string, id int, body PostLaptopsIdLogsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostLaptopsIdLogsRequestWithBody(server, id, "application/json", bodyReader)
}

// NewPostLaptopsIdLogsRequestWithBody constructs an http.Request for the PostLaptopsIdLogs method, with any body, and a specified content type
func NewPostLaptopsIdLogsRequestWithBody(server string, id int, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/laptops/%s/logs", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteLaptopsIdLogsLogIdRequest constructs an http.Request for the DeleteLaptopsIdLogsLogId method
func NewDeleteLaptopsIdLogsLogIdRequest(server string, id int, logId int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "logId", logId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/laptops/%s/logs/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutLaptopsIdLogsLogIdRequest calls the generic PutLaptopsIdLogsLogId builder with application/json body
func NewPutLaptopsIdLogsLogIdRequest(server string, id int, logId int, body PutLaptopsIdLogsLogIdJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutLaptopsIdLogsLogIdRequestWithBody(server, id, logId, "application/json", bodyReader)
}

// NewPutLaptopsIdLogsLogIdRequestWithBody constructs an http.Request for the PutLaptopsIdLogsLogId method, with any body, and a specified content type
func NewPutLaptopsIdLogsLogIdRequestWithBody(server string, id int, logId int, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "logId", logId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/laptops/%s/logs/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// GetLaptopsWithResponse Liste aller Laptops abrufen
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /laptops (the `GetLaptops` operationId).
	GetLaptopsWithResponse(ctx context.Context, params *GetLaptopsParams, reqEditors ...RequestEditorFn) (*GetLaptopsResponse, error)

	// PostLaptopsWithBodyWithResponse Neuen Laptop zur Reparatur erfassen
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /laptops (the `PostLaptops` operationId).
	PostLaptopsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostLaptopsResponse, error)

	// PostLaptopsWithResponse Neuen Laptop zur Reparatur erfassen
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /laptops (the `PostLaptops` operationId).
	PostLaptopsWithResponse(ctx context.Context, body PostLaptopsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostLaptopsResponse, error)

	// DeleteLaptopsIdWithResponse Reparierten oder ausgemusterten Laptop l├Âschen
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /laptops/{id} (the `DeleteLaptopsId` operationId).
	DeleteLaptopsIdWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*DeleteLaptopsIdResponse, error)

	// GetLaptopsIdWithResponse Einzelnen Laptop samt Logs abrufen
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /laptops/{id} (the `GetLaptopsId` operationId).
	GetLaptopsIdWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*GetLaptopsIdResponse, error)

	// PutLaptopsIdWithBodyWithResponse Laptop-Daten oder Fehlerstatus aktualisieren
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /laptops/{id} (the `PutLaptopsId` operationId).
	PutLaptopsIdWithBodyWithResponse(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutLaptopsIdResponse, error)

	// PutLaptopsIdWithResponse Laptop-Daten oder Fehlerstatus aktualisieren
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /laptops/{id} (the `PutLaptopsId` operationId).
	PutLaptopsIdWithResponse(ctx context.Context, id int, body PutLaptopsIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PutLaptopsIdResponse, error)

	// PostLaptopsIdLogsWithBodyWithResponse IT-Log-Eintrag hinzuf├╝gen
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /laptops/{id}/logs (the `PostLaptopsIdLogs` operationId).
	PostLaptopsIdLogsWithBodyWithResponse(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostLaptopsIdLogsResponse, error)

	// PostLaptopsIdLogsWithResponse IT-Log-Eintrag hinzuf├╝gen
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /laptops/{id}/logs (the `PostLaptopsIdLogs` operationId).
	PostLaptopsIdLogsWithResponse(ctx context.Context, id int, body PostLaptopsIdLogsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostLaptopsIdLogsResponse, error)

	// DeleteLaptopsIdLogsLogIdWithResponse IT-Log-Eintrag l├Âschen
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /laptops/{id}/logs/{logId} (the `DeleteLaptopsIdLogsLogId` operationId).
	DeleteLaptopsIdLogsLogIdWithResponse(ctx context.Context, id int, logId int, reqEditors ...RequestEditorFn) (*DeleteLaptopsIdLogsLogIdResponse, error)

	// PutLaptopsIdLogsLogIdWithBodyWithResponse Existierenden IT-Log-Eintrag aktualisieren
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /laptops/{id}/logs/{logId} (the `PutLaptopsIdLogsLogId` operationId).
	PutLaptopsIdLogsLogIdWithBodyWithResponse(ctx context.Context, id int, logId int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutLaptopsIdLogsLogIdResponse, error)

	// PutLaptopsIdLogsLogIdWithResponse Existierenden IT-Log-Eintrag aktualisieren
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /laptops/{id}/logs/{logId} (the `PutLaptopsIdLogsLogId` operationId).
	PutLaptopsIdLogsLogIdWithResponse(ctx context.Context, id int, logId int, body PutLaptopsIdLogsLogIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PutLaptopsIdLogsLogIdResponse, error)
}

type GetLaptopsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *[]Laptop
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetLaptopsResponse) GetJSON200() *[]Laptop {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetLaptopsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetLaptopsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetLaptopsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetLaptopsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostLaptopsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *Laptop
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r PostLaptopsResponse) GetJSON201() *Laptop {
	return r.JSON201
}

// GetBody returns the raw response body bytes
func (r PostLaptopsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PostLaptopsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostLaptopsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostLaptopsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteLaptopsIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r DeleteLaptopsIdResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DeleteLaptopsIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteLaptopsIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteLaptopsIdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetLaptopsIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Laptop
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetLaptopsIdResponse) GetJSON200() *Laptop {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetLaptopsIdResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetLaptopsIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetLaptopsIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetLaptopsIdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PutLaptopsIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Laptop
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r PutLaptopsIdResponse) GetJSON200() *Laptop {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r PutLaptopsIdResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PutLaptopsIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutLaptopsIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PutLaptopsIdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostLaptopsIdLogsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *LogEintrag
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r PostLaptopsIdLogsResponse) GetJSON201() *LogEintrag {
	return r.JSON201
}

// GetBody returns the raw response body bytes
func (r PostLaptopsIdLogsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PostLaptopsIdLogsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostLaptopsIdLogsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostLaptopsIdLogsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteLaptopsIdLogsLogIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r DeleteLaptopsIdLogsLogIdResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DeleteLaptopsIdLogsLogIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteLaptopsIdLogsLogIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteLaptopsIdLogsLogIdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PutLaptopsIdLogsLogIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *LogEintrag
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r PutLaptopsIdLogsLogIdResponse) GetJSON200() *LogEintrag {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r PutLaptopsIdLogsLogIdResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PutLaptopsIdLogsLogIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutLaptopsIdLogsLogIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PutLaptopsIdLogsLogIdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetLaptopsWithResponse Liste aller Laptops abrufen
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /laptops (the `GetLaptops` operationId).
func (c *ClientWithResponses) GetLaptopsWithResponse(ctx context.Context, params *GetLaptopsParams, reqEditors ...RequestEditorFn) (*GetLaptopsResponse, error) {
	rsp, err := c.GetLaptops(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetLaptopsResponse(rsp)
}

// PostLaptopsWithBodyWithResponse Neuen Laptop zur Reparatur erfassen
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /laptops (the `PostLaptops` operationId).
func (c *ClientWithResponses) PostLaptopsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostLaptopsResponse, error) {
	rsp, err := c.PostLaptopsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostLaptopsResponse(rsp)
}

// PostLaptopsWithResponse Neuen Laptop zur Reparatur erfassen
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /laptops (the `PostLaptops` operationId).
func (c *ClientWithResponses) PostLaptopsWithResponse(ctx context.Context, body PostLaptopsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostLaptopsResponse, error) {
	rsp, err := c.PostLaptops(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostLaptopsResponse(rsp)
}

// DeleteLaptopsIdWithResponse Reparierten oder ausgemusterten Laptop l├Âschen
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with DELETE /laptops/{id} (the `DeleteLaptopsId` operationId).
func (c *ClientWithResponses) DeleteLaptopsIdWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*DeleteLaptopsIdResponse, error) {
	rsp, err := c.DeleteLaptopsId(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteLaptopsIdResponse(rsp)
}

// GetLaptopsIdWithResponse Einzelnen Laptop samt Logs abrufen
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /laptops/{id} (the `GetLaptopsId` operationId).
func (c *ClientWithResponses) GetLaptopsIdWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*GetLaptopsIdResponse, error) {
	rsp, err := c.GetLaptopsId(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetLaptopsIdResponse(rsp)
}

// PutLaptopsIdWithBodyWithResponse Laptop-Daten oder Fehlerstatus aktualisieren
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /laptops/{id} (the `PutLaptopsId` operationId).
func (c *ClientWithResponses) PutLaptopsIdWithBodyWithResponse(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutLaptopsIdResponse, error) {
	rsp, err := c.PutLaptopsIdWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutLaptopsIdResponse(rsp)
}

// PutLaptopsIdWithResponse Laptop-Daten oder Fehlerstatus aktualisieren
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /laptops/{id} (the `PutLaptopsId` operationId).
func (c *ClientWithResponses) PutLaptopsIdWithResponse(ctx context.Context, id int, body PutLaptopsIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PutLaptopsIdResponse, error) {
	rsp, err := c.PutLaptopsId(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutLaptopsIdResponse(rsp)
}

// PostLaptopsIdLogsWithBodyWithResponse IT-Log-Eintrag hinzuf├╝gen
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /laptops/{id}/logs (the `PostLaptopsIdLogs` operationId).
func (c *ClientWithResponses) PostLaptopsIdLogsWithBodyWithResponse(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostLaptopsIdLogsResponse, error) {
	rsp, err := c.PostLaptopsIdLogsWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostLaptopsIdLogsResponse(rsp)
}

// PostLaptopsIdLogsWithResponse IT-Log-Eintrag hinzuf├╝gen
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /laptops/{id}/logs (the `PostLaptopsIdLogs` operationId).
func (c *ClientWithResponses) PostLaptopsIdLogsWithResponse(ctx context.Context, id int, body PostLaptopsIdLogsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostLaptopsIdLogsResponse, error) {
	rsp, err := c.PostLaptopsIdLogs(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostLaptopsIdLogsResponse(rsp)
}

// DeleteLaptopsIdLogsLogIdWithResponse IT-Log-Eintrag l├Âschen
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with DELETE /laptops/{id}/logs/{logId} (the `DeleteLaptopsIdLogsLogId` operationId).
func (c *ClientWithResponses) DeleteLaptopsIdLogsLogIdWithResponse(ctx context.Context, id int, logId int, reqEditors ...RequestEditorFn) (*DeleteLaptopsIdLogsLogIdResponse, error) {
	rsp, err := c.DeleteLaptopsIdLogsLogId(ctx, id, logId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteLaptopsIdLogsLogIdResponse(rsp)
}

// PutLaptopsIdLogsLogIdWithBodyWithResponse Existierenden IT-Log-Eintrag aktualisieren
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /laptops/{id}/logs/{logId} (the `PutLaptopsIdLogsLogId` operationId).
func (c *ClientWithResponses) PutLaptopsIdLogsLogIdWithBodyWithResponse(ctx context.Context, id int, logId int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutLaptopsIdLogsLogIdResponse, error) {
	rsp, err := c.PutLaptopsIdLogsLogIdWithBody(ctx, id, logId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutLaptopsIdLogsLogIdResponse(rsp)
}

// PutLaptopsIdLogsLogIdWithResponse Existierenden IT-Log-Eintrag aktualisieren
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /laptops/{id}/logs/{logId} (the `PutLaptopsIdLogsLogId` operationId).
func (c *ClientWithResponses) PutLaptopsIdLogsLogIdWithResponse(ctx context.Context, id int, logId int, body PutLaptopsIdLogsLogIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PutLaptopsIdLogsLogIdResponse, error) {
	rsp, err := c.PutLaptopsIdLogsLogId(ctx, id, logId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutLaptopsIdLogsLogIdResponse(rsp)
}

// ParseGetLaptopsResponse parses an HTTP response from a GetLaptopsWithResponse call
func ParseGetLaptopsResponse(rsp *http.Response) (*GetLaptopsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetLaptopsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Laptop
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case rsp.StatusCode == 400:
		break // No content-type

	}

	return response, nil
}

// ParsePostLaptopsResponse parses an HTTP response from a PostLaptopsWithResponse call
func ParsePostLaptopsResponse(rsp *http.Response) (*PostLaptopsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostLaptopsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Laptop
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case rsp.StatusCode == 400:
		break // No content-type

	}

	return response, nil
}

// ParseDeleteLaptopsIdResponse parses an HTTP response from a DeleteLaptopsIdWithResponse call
func ParseDeleteLaptopsIdResponse(rsp *http.Response) (*DeleteLaptopsIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteLaptopsIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetLaptopsIdResponse parses an HTTP response from a GetLaptopsIdWithResponse call
func ParseGetLaptopsIdResponse(rsp *http.Response) (*GetLaptopsIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetLaptopsIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Laptop
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case rsp.StatusCode == 400:
		break // No content-type

	case rsp.StatusCode == 404:
		break // No content-type

	}

	return response, nil
}

// ParsePutLaptopsIdResponse parses an HTTP response from a PutLaptopsIdWithResponse call
func ParsePutLaptopsIdResponse(rsp *http.Response) (*PutLaptopsIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutLaptopsIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Laptop
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case rsp.StatusCode == 400:
		break // No content-type

	case rsp.StatusCode == 404:
		break // No content-type

	}

	return response, nil
}

// ParsePostLaptopsIdLogsResponse parses an HTTP response from a PostLaptopsIdLogsWithResponse call
func ParsePostLaptopsIdLogsResponse(rsp *http.Response) (*PostLaptopsIdLogsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostLaptopsIdLogsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest LogEintrag
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case rsp.StatusCode == 400:
		break // No content-type

	case rsp.StatusCode == 404:
		break // No content-type

	}

	return response, nil
}

// ParseDeleteLaptopsIdLogsLogIdResponse parses an HTTP response from a DeleteLaptopsIdLogsLogIdWithResponse call
func ParseDeleteLaptopsIdLogsLogIdResponse(rsp *http.Response) (*DeleteLaptopsIdLogsLogIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteLaptopsIdLogsLogIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParsePutLaptopsIdLogsLogIdResponse parses an HTTP response from a PutLaptopsIdLogsLogIdWithResponse call
func ParsePutLaptopsIdLogsLogIdResponse(rsp *http.Response) (*PutLaptopsIdLogsLogIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutLaptopsIdLogsLogIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest LogEintrag
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case rsp.StatusCode == 400:
		break // No content-type

	case rsp.StatusCode == 404:
		break // No content-type

	}

	return response, nil
}
