/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/laptops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste aller Laptops abrufen */
        get: {
            parameters: {
                query?: {
                    fehler?: components["schemas"]["FehlerKategorie"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Erfolgreich */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Laptop"][];
                    };
                };
                /** @description Ungültige Anfrageparameter */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Neuen Laptop zur Reparatur erfassen */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LaptopInput"];
                };
            };
            responses: {
                /** @description Laptop angelegt */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Laptop"];
                    };
                };
                /** @description Ungültige Eingabedaten (z.B. fehlende Pflichtfelder) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/laptops/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Einzelnen Laptop samt Logs abrufen */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Erfolgreich */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Laptop"];
                    };
                };
                /** @description Ungültiges ID-Format */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Laptop nicht gefunden */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Laptop-Daten oder Fehlerstatus aktualisieren */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LaptopInput"];
                };
            };
            responses: {
                /** @description Laptop erfolgreich aktualisiert */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Laptop"];
                    };
                };
                /** @description Ungültige Eingabedaten oder ID-Format */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Laptop nicht gefunden */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Reparierten oder ausgemusterten Laptop löschen */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Laptop erfolgreich gelöscht (Kein Inhalt im Body) */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Ungültiges ID-Format */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Laptop nicht gefunden */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/laptops/{id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** IT-Log-Eintrag hinzufügen */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LogEintragInput"];
                };
            };
            responses: {
                /** @description Log-Eintrag erfolgreich hinzugefügt */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LogEintrag"];
                    };
                };
                /** @description Ungültige Eingabedaten oder ID-Format */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Laptop nicht gefunden */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/laptops/{id}/logs/{logId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Existierenden IT-Log-Eintrag aktualisieren */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                    logId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LogEintragInput"];
                };
            };
            responses: {
                /** @description Log-Eintrag erfolgreich aktualisiert */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LogEintrag"];
                    };
                };
                /** @description Ungültige Eingabedaten oder ID-Format */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Laptop oder Log-Eintrag nicht gefunden */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** IT-Log-Eintrag löschen */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                    logId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Log-Eintrag erfolgreich gelöscht */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Ungültiges ID-Format */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Laptop oder Log-Eintrag nicht gefunden */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        FehlerKategorie: "DISPLAY_SCHADEN" | "AKKU_DEFEKT" | "TASTATUR_DEFEKT" | "SOFTWARE_OS" | "KEIN_FEHLER";
        Laptop: {
            /** @example 1234 */
            id: number;
            /** @example HP EliteBook 840 */
            name: string;
            /** @example HP */
            marke: string;
            /** @example Windows 11 */
            os: string;
            fehler: components["schemas"]["FehlerKategorie"];
            it_logs?: components["schemas"]["LogEintrag"][];
        };
        LaptopInput: {
            /** @example HP EliteBook 840 */
            name: string;
            /** @example HP */
            marke: string;
            /** @example Windows 11 */
            os: string;
            fehler: components["schemas"]["FehlerKategorie"];
        };
        LogEintrag: {
            /** @example 1 */
            id: number;
            /**
             * Format: date-time
             * @example 2026-09-02T10:15:00Z
             */
            timestamp: string;
            /** @example m.mustermann */
            bearbeiter: string;
            /** @example Gerät erfolgreich repariert. */
            notiz: string;
        };
        LogEintragInput: {
            /** @example m.mustermann */
            bearbeiter: string;
            /** @example Gerät erfolgreich repariert. */
            notiz: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
